### ISSUE TITLE
Making runtime config change did not work

### ISSUE THREAD

**Issue by panaobo** [envoyproxy/ratelimit#132]
Hello, 

This is my docker compose:
```  ratelimit:
    image: envoyproxy/ratelimit:v1.4.0
    container_name: ratelimit
    command: /usr/local/bin/ratelimit
    ports:
      - 8050:8080
      - 8051:8081
      - 6070:6070
    volumes:
      - binary:/usr/local/bin/
      - ./examples:/data
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=/
      - RUNTIME_IGNOREDOTFILES=true
    depends_on:
      - redis
```

When I make changes in `/data/config/config.yaml`, the event is not catched.

However, if I do something in root `/`, I can see logs like :
```
ratelimit         | time="2020-04-10T03:47:58Z" level=debug msg="Got event \"//config.yaml\": REMOVE"
ratelimit         | time="2020-04-10T03:47:58Z" level=debug msg="Got event \"//config.yaml\": CREATE"
ratelimit         | time="2020-04-10T03:47:58Z" level=debug msg="Got event \"//config.yaml\": WRITE"
ratelimit         | time="2020-04-10T03:47:58Z" level=debug msg="Got event \"//config.yaml\": WRITE"
```

When I set `- RUNTIME_ROOT=/data/sub/sub1`, then the event would be caught if I make changes in `/data/sub`

Not sure if it's a bug or I missed something here.

Thanks in advance!

**Comment by ysawa0** [comment]
I think there is an issue with the file watcher used by default -- `SymlinkRefresher`
https://github.com/envoyproxy/ratelimit/blob/master/src/server/server_impl.go#L144

I had similar issues trying to get config hot reloading working with k8s ConfigMaps and had to switch the code to use `&loader.DirectoryRefresher{}` instead of `&loader.SymlinkRefresher`. 

The changes I made:

Add DirectoryRefresher in src/server/server_impl.go and remove SymlinkRefresher
```
	ret.runtime = loader.New(
		s.RuntimePath,
		s.RuntimeSubdirectory,
		ret.store.Scope("runtime"),
		//&loader.SymlinkRefresher{RuntimePath: s.RuntimePath},
		&loader.DirectoryRefresher{},
		loaderOpts...)
```

Comment out Lines 77 to 79 in https://github.com/envoyproxy/ratelimit/blob/master/src/service/ratelimit.go#L77-L79

(Need this because DirectoryRefresher doesn't watch subdirectories)
```
	for _, key := range snapshot.Keys() {
		//if !strings.HasPrefix(key, "config.") {
		//	continue
		//}

		files = append(files, config.RateLimitConfigToLoad{key, snapshot.Get(key)})
	}
```

**Comment by panaobo** [comment]
Thank you! I will try it out!
