### ISSUE TITLE
Proposal: Enable emittance of total service call + response time metrics

### ISSUE THREAD

**Issue by thao-wish** [envoyproxy/ratelimit#234]
Currently ratelimit emits service error metrics that can be used to monitor error counts, but it doesn't emit total number of service calls or response time metrics that would enable us to monitor Requests Per Second/latency.

In our case, being able to monitor these metrics is an absolute necessity. Since the ratelimit service is used in production at lyft, I'm wondering if the team can share some insights on how RPS/latency metrics are measured at lyft. I can also work on a PR to enable these metrics.

**Comment by dweitzman** [comment]
Stats does seems like an area that could use improvement. Not at lyft, but I can tell you what we've done.

For the moment we monitor latency and errors at the client side, with the rate limiter running as a sidecar on the same machine. The stats we use from the rate limiter itself are config loads and errors, memcache hit rates, per-descriptor stats, and a hacky total descriptor hit rate (which opentsdb is willing to do even though it's a aggregating across ton of metric names instead of something simple and easy like tags)

I briefly tested what happens when you get time/latency statistics from the `gostats` library and the output format wasn't compatible with our metrics agent. I think maybe it outputs floating point numbers and that wasn't accepted by the agent, or something like that (`statsd` is not a standardized protocol).

**Comment by mattklein123** [comment]
> In our case, being able to monitor these metrics is an absolute necessity. Since the ratelimit service is used in production at lyft, I'm wondering if the team can share some insights on how RPS/latency metrics are measured at lyft. I can also work on a PR to enable these metrics.

We use Envoy :)
